#!/bin/bash -ex

# Update yum
yum -y update

# Add node's source repo
curl -sL https://rpm.nodesource.com/setup_15.x | bash -

#Install nodejs1
yum -y install nodejs


# Create a dedicated directory for the application
mkdir -p /var/app

# Get the app from Amazon S3
wget https://aws-tc-largeobjects.s3-us-west-2.amazonaws.com/ILT-TF-100-TECESS-5/app/app.zip

# Extract it into a desired folder
unzip app.zip -d /var/app/
cd /var/app/

# Install dependencies
npm install

# Start your app
npm start